### ISSUE TITLE
Geekdom coworking member interested in your account name

### ISSUE THREAD

**Issue by emilyrbowe** [Nicoville/GeekBlog#1]
Hi -- I'm a member of Geekdom, the coworking space in San Antonio, and am trying to create an organization where members and staff can collaborate on projects and resources. I saw that your account was created in 2010, but hasn't been used in the last year. Also, it looks like your GeekBlog isn't hosted anymore, so I was wondering if you would consider renaming this account so that we could take over the username "Geekdom"? Let me know via issue if you would be interested in doing this. GitHub TOS prohibit sale of a domain (https://help.github.com/articles/name-squatting-policy/), which is why I'm asking if you would consider renaming your account. 

Looking forward to your response.

**Comment by Nicoville** [comment]
Looks like you have a worthy cause. Enjoy

**Comment by emilyrbowe** [comment]
Thank you!
